import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { ThemeProvider } from "../providers/ThemeProvider";
import Sidebar from "../components/Sidebar";
import "./globals.css";

const lato = Lato({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Todo List | Dashboard",
  description: "This todo list tasks generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lato.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex min-h-screen">
            <Sidebar />
            <main className="flex-1 lg:ml-0">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
